name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-25.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: 109.176.199.65
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /root/deploy.sh